sudo: true
os: linux
dist: focal
cache: false
language: generic

before_script:
- export adx_dir=adx-cli
- git fetch --depth=10000
- wget https://dx.appirio.com/downloads/adx-cli-linux.tar.gz -P $adx_dir
- (cd $adx_dir && tar -xzf adx-cli-linux.tar.gz)
- export PATH=$(pwd)/$adx_dir:$PATH

stages:
  # - name: sonarqube_scan
  #   if: tag IS blank
  - name: version_package
    if: branch = master
  - name: install_to_SIT
    if: branch = master

# Ideally, This job should be triggered manually. But currently travis ci does not support manual actions.
# This 'install to UAT' job gets triggered whenever there is matching tag on commit.
# This will be updated in future when travis ci starts supporting manual trigger.
  - name: install_to_UAT
    if: tag =~ uat-*

# Ideally, This job should be triggered manually. But currently travis ci does not support manual actions.
# This 'install to PROD' job gets triggered whenever there is matching tag on commit.
# This will be updated in future when travis ci starts supporting manual trigger.
  - name: install_to_PROD
    if: tag =~ prod-*

jobs:

  include:

      # - stage: sonarqube_scan
      #   name: sonarqube_scan
      #   before_script:
      #     - export sonar_dir=sonarqube
      #     - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip -P $sonar_dir
      #     - (cd $sonar_dir && unzip sonar-scanner-cli-4.0.0.1744-linux.zip)
      #     - export PATH=$(pwd)/$sonar_dir/sonar-scanner-4.0.0.1744-linux/bin:$PATH
      #   script: sonar-scanner -Dsonar.login=$SONAR_ENT_LOGIN -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300

      - stage: version_package
        name: version_package
        script:
          - adx sfdx:package:publish --installationkeybypass

      - stage: install_to_SIT
        name: install_to_SIT
        script:
          - adx sfdx:package:install --installationkeybypass --destination SIT

      - stage: install_to_UAT
        name: install_to_UAT
        script:
          - adx sfdx:package:install --installationkeybypass --destination UAT

      - stage: install_to_PROD
        name: install_to_PROD
        script:
          - adx sfdx:package:install --installationkeybypass --destination PROD --release
