sudo: true
os: linux
cache: false
language: generic

git:
  depth: false

before_install:
- wget https://appiriodx-website-prod.s3.amazonaws.com/downloads/adx-dev-cli-linux.tar.gz -P adx
- (cd adx && tar -xzf adx-dev-cli-linux.tar.gz)
- export PATH=$(pwd)/adx:$PATH

stages:
  - name: sonarqube_scan_publish
  - name: publish
    if: branch = master
  - name: install_sit
    if: branch = master
  - name: install_uat
    if: tag =~ uat-*
  - name: install_prod
    if: tag =~ prod-*

jobs:

  include:

      - stage: sonarqube_scan_publish
        name: sonarqube_scan_publish
        before_script:
          - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip -P adx
          - (cd adx && unzip sonar-scanner-cli-3.0.3.778-linux.zip)
          - export PATH=$(pwd)/adx/sonar-scanner-3.0.3.778-linux/bin:$PATH
        script: sonar-scanner -Dsonar.sources=. -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=publish

      - stage: publish
        name: version_package
        script:
          - adx sfdx:package:publish --installationkeybypass

      - stage: install_sit
        name: install_to_SIT
        script:
          - adx sfdx:package:install --installationkeybypass --destination SIT

      - stage: install_uat
        name: install_to_UAT
        script:
          - adx sfdx:package:install --installationkeybypass --destination UAT

      - stage: install_prod
        name: install_to_PROD
        script:
          - adx sfdx:package:install --installationkeybypass --destination PROD --release
