sudo: true
os: linux
cache: false
language: generic

before_script:
- export adx_dir=adx-cli
- git fetch --depth=10000
- wget https://appiriodx-website-prod.s3.amazonaws.com/downloads/adx-dev-cli-linux.tar.gz -P $adx_dir
- (cd $adx_dir && tar -xzf adx-dev-cli-linux.tar.gz)
- export PATH=$(pwd)/$adx_dir:$PATH

stages:
  - name: sonarqube_scan_publish
    if: (branch = master) OR (branch =~ feature\/*)
  - name: publish
    if: branch = master
  - name: install_sit
    if: branch = master

# Ideally, This job should be triggered manually. But currently travis ci does not support manual actions.
# This 'install to UAT' job gets triggered whenever there is matching tag on commit.
# This will be updated in future when travis ci starts supporting manual trigger.
  - name: install_uat
    if: tag =~ uat-*

# Ideally, This job should be triggered manually. But currently travis ci does not support manual actions.
# This 'install to PROD' job gets triggered whenever there is matching tag on commit.
# This will be updated in future when travis ci starts supporting manual trigger.
  - name: install_prod
    if: tag =~ prod-*

jobs:

  include:

      - stage: sonarqube_scan_publish
        name: sonarqube_scan_publish
        before_script:
          - export sonar_dir=sonarqube
          - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip -P $sonar_dir
          - (cd $sonar_dir && unzip sonar-scanner-cli-3.0.3.778-linux.zip)
          - export PATH=$(pwd)/$sonar_dir/sonar-scanner-3.0.3.778-linux/bin:$PATH
        script: sonar-scanner -Dsonar.sources=. -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=publish

      - stage: publish
        name: version_package
        script:
          - adx sfdx:package:publish --installationkeybypass

      - stage: install_sit
        name: install_to_SIT
        script:
          - adx sfdx:package:install --installationkeybypass --destination SIT

      - stage: install_uat
        name: install_to_UAT
        script:
          - adx sfdx:package:install --installationkeybypass --destination UAT

      - stage: install_prod
        name: install_to_PROD
        script:
          - adx sfdx:package:install --installationkeybypass --destination PROD --release
